site_name: Boxel 3D Modding Documentation
nav:
  - Introduction: index.md
  - Getting Started: gettingstarted.md
  - Events: events.md
  - About: about.md
site_url: https://mydomain.org/mysite
repo_url: https://github.com/doppl3r/boxel-3d-support
repo_name: Boxel 3D Support
markdown_extensions: 
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets
  - attr_list
  - md_in_html
  - abbr
plugins:
  - search
theme:
  name: material
  custom_dir: overrides
  features:
    - header.autohide
    - navigation.footer
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
      primary: cyan 
      accent: pink
      name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
      name: Switch to light mode
      primary: pink 
      accent: cyan
  logo: images/Icon2.png
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  favicon: images/Icon2.png
  font:
    text: Comfortaa
    code: Poppins
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/youtube 
      link: https://www.youtube.com/@dopplercreative
    - icon: fontawesome/brands/discord 
      link: https://discord.gg/wYTCk3jVua